#wx_mock.py  20Jul2024  crs, Author
""" 
Simple Mock testing
"""
from unittest.mock import MagicMock

class MMagic(MagicMock):
    """
    Simple every function class
    """
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        title = "default title"
        if "title" in kwargs:
            title = kwargs["title"]
        self.title = title
        
    def say(self, msg="Default Msg"):
        print(self.title, msg)
        
print("Test Begin")
print("__init__, say are extended member functions")
print("a, b, c are generated by calls")    
mm =  MMagic(title="Testing")
mm.i.return_value = 1
mm.j.return_value = 1
mm.a()
mm.say("Hi")
mm.b()
mm.c()

print(f"mm.data_member:{mm.data_member}")
print(f"Extended members: mm.say:{mm.say}")
print(f"generated: mm.a:{mm.a}, mm.b:{mm.b}, mm.c:{mm.c}")
print(f"mm.i() > mm.j(): {mm.i() > mm.j()}")
print("Test End")
